project_id = "leykexzdvatuyitkxdxs"

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.vwe-taxatie]
verify_jwt = false

[functions.analyze-deal]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.moneybird]
verify_jwt = false

[functions.make-webhook-handler]
verify_jwt = false

[functions.generate-social-post]
verify_jwt = false

[functions.fetch-google-reviews]
verify_jwt = false

[functions.estimate-trade-in-value]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

