project_id = "leykexzdvatuyitkxdxs"

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.vwe-taxatie]
verify_jwt = false

[functions.analyze-deal]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.moneybird]
verify_jwt = false

[functions.make-webhook-handler]
verify_jwt = false

