ALTER TABLE public.vehicle_sales
  ADD COLUMN IF NOT EXISTS inruil_van_toepassing boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS inruil_type text,
  ADD COLUMN IF NOT EXISTS inruil_kenteken text,
  ADD COLUMN IF NOT EXISTS inruil_merk text,
  ADD COLUMN IF NOT EXISTS inruil_model text,
  ADD COLUMN IF NOT EXISTS inruil_bouwjaar integer,
  ADD COLUMN IF NOT EXISTS inruil_kilometerstand integer,
  ADD COLUMN IF NOT EXISTS inruil_kleur text,
  ADD COLUMN IF NOT EXISTS inruil_chassisnummer text,
  ADD COLUMN IF NOT EXISTS inruil_waarde numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS inruil_betaalwijze text,
  ADD COLUMN IF NOT EXISTS inruil_verkoper_voornaam text,
  ADD COLUMN IF NOT EXISTS inruil_verkoper_achternaam text,
  ADD COLUMN IF NOT EXISTS inruil_verkoper_geboortedatum date,
  ADD COLUMN IF NOT EXISTS inruil_verkoper_adres text,
  ADD COLUMN IF NOT EXISTS inruil_verkoper_postcode text,
  ADD COLUMN IF NOT EXISTS inruil_verkoper_woonplaats text,
  ADD COLUMN IF NOT EXISTS inruil_verkoper_telefoon text,
  ADD COLUMN IF NOT EXISTS inruil_bedrijfsnaam text,
  ADD COLUMN IF NOT EXISTS inruil_kvk_nummer text,
  ADD COLUMN IF NOT EXISTS inruil_btw_nummer text,
  ADD COLUMN IF NOT EXISTS inruil_contactpersoon text,
  ADD COLUMN IF NOT EXISTS inruil_inkoopverklaring_id uuid REFERENCES public.inkoopverklaringen(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS stap6_afgerond boolean NOT NULL DEFAULT false;